# Generated by Django 3.2.5 on 2021-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_aplly_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplly',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
